export const extraProducts5 = [
  // --- EXTREME BUDGET GPUs ---
  { sku: 'GPU-NVIDIA-750TI', categorySlug: 'gpus', name: 'NVIDIA GeForce GTX 750 Ti 2GB (Used)', slug: 'nvidia-gtx-750-ti-2gb-used', brand: 'NVIDIA', basePrice: 12000, description: 'The granddaddy of budget gaming. Still plays older esports titles well.', specs: { vram: '2GB' }, compatibility: { category: 'GPU', tdp: 60 } },
  { sku: 'GPU-AMD-RX470-4GB', categorySlug: 'gpus', name: 'Sapphire Radeon RX 470 4GB (Used)', slug: 'sapphire-rx-470-4gb-used', brand: 'Sapphire', basePrice: 16500, description: 'Incredible value for 1080p gaming on older titles.', specs: { vram: '4GB' }, compatibility: { category: 'GPU', tdp: 120 } },
  { sku: 'GPU-NVIDIA-960-4GB', categorySlug: 'gpus', name: 'ASUS GeForce GTX 960 4GB (Used)', slug: 'asus-gtx-960-4gb-used', brand: 'ASUS', basePrice: 15000, description: 'Solid 1080p performer for very tight budgets.', specs: { vram: '4GB' }, compatibility: { category: 'GPU', tdp: 120 } },
  { sku: 'GPU-NVIDIA-1050TI', categorySlug: 'gpus', name: 'MSI GeForce GTX 1050 Ti 4GB (Used)', slug: 'msi-gtx-1050-ti-4gb-used', brand: 'MSI', basePrice: 19500, description: 'Doesn\'t require external power. Plug and play budget king.', specs: { vram: '4GB' }, compatibility: { category: 'GPU', tdp: 75 } },
  { sku: 'GPU-AMD-RX570-4GB', categorySlug: 'gpus', name: 'Gigabyte Radeon RX 570 4GB (Used)', slug: 'gigabyte-rx-570-4gb-used', brand: 'GIGABYTE', basePrice: 18000, description: 'Slightly cut down RX 580, excellent for modern esports.', specs: { vram: '4GB' }, compatibility: { category: 'GPU', tdp: 150 } },
  { sku: 'GPU-NVIDIA-1650-4GB', categorySlug: 'gpus', name: 'ZOTAC GeForce GTX 1650 4GB (Used)', slug: 'zotac-gtx-1650-4gb-used', brand: 'ZOTAC', basePrice: 28500, description: 'Great 1080p entry level card with modern architecture.', specs: { vram: '4GB' }, compatibility: { category: 'GPU', tdp: 75 } },

  // --- BUDGET CPUs ---
  { sku: 'CPU-INT-I5-3470', categorySlug: 'processors', name: 'Intel Core i5-3470 (Used)', slug: 'intel-core-i5-3470-used', brand: 'Intel', basePrice: 2500, description: 'Quad core processor for the cheapest possible functional PC.', specs: { cores: '4', threads: '4', socket: 'LGA1155' }, compatibility: { category: 'CPU', socket: 'LGA1155', tdp: 77 } },
  { sku: 'CPU-INT-I5-6500', categorySlug: 'processors', name: 'Intel Core i5-6500 (Used)', slug: 'intel-core-i5-6500-used', brand: 'Intel', basePrice: 5500, description: '6th Gen entry into DDR4 territory.', specs: { cores: '4', threads: '4', socket: 'LGA1151' }, compatibility: { category: 'CPU', socket: 'LGA1151', tdp: 65 } },
  { sku: 'CPU-INT-I7-4790', categorySlug: 'processors', name: 'Intel Core i7-4790 (Used)', slug: 'intel-core-i7-4790-used', brand: 'Intel', basePrice: 8500, description: 'The absolute best you can get for 4th Gen DDR3 systems.', specs: { cores: '4', threads: '8', socket: 'LGA1150' }, compatibility: { category: 'CPU', socket: 'LGA1150', tdp: 84 } },
  { sku: 'CPU-AMD-R5-1600', categorySlug: 'processors', name: 'AMD Ryzen 5 1600 (Used)', slug: 'amd-ryzen-5-1600-used', brand: 'AMD', basePrice: 11000, description: '6 Cores and 12 Threads for cheap! The CPU that started the Ryzen revolution.', specs: { cores: '6', threads: '12', socket: 'AM4' }, compatibility: { category: 'CPU', socket: 'AM4', tdp: 65 } },
  { sku: 'CPU-AMD-R5-2600', categorySlug: 'processors', name: 'AMD Ryzen 5 2600 (Used)', slug: 'amd-ryzen-5-2600-used', brand: 'AMD', basePrice: 14000, description: 'Excellent budget 6-core processor for early AM4 builds.', specs: { cores: '6', threads: '12', socket: 'AM4' }, compatibility: { category: 'CPU', socket: 'AM4', tdp: 65 } },
  { sku: 'CPU-INT-I3-9100F', categorySlug: 'processors', name: 'Intel Core i3-9100F (Used)', slug: 'intel-core-i3-9100f-used', brand: 'Intel', basePrice: 9500, description: 'Snappy quad core without integrated graphics for cheap 9th gen builds.', specs: { cores: '4', threads: '4', socket: 'LGA1151' }, compatibility: { category: 'CPU', socket: 'LGA1151', tdp: 65 } },

  // --- BUDGET MOTHERBOARDS ---
  { sku: 'MB-INT-H61', categorySlug: 'motherboards', name: 'Generic H61 Motherboard LGA1155', slug: 'generic-h61-lga1155', brand: 'Generic', basePrice: 3800, description: 'Brand new generic board for 2nd and 3rd Gen Intel.', specs: { socket: 'LGA1155', chipset: 'H61', formFactor: 'Micro-ATX', memoryType: 'DDR3' }, compatibility: { category: 'MOTHERBOARD', socket: 'LGA1155', formFactor: 'Micro-ATX' } },
  { sku: 'MB-INT-B85', categorySlug: 'motherboards', name: 'Generic B85 Motherboard LGA1150', slug: 'generic-b85-lga1150', brand: 'Generic', basePrice: 4800, description: 'Motherboard for 4th Gen Intel processors.', specs: { socket: 'LGA1150', chipset: 'B85', formFactor: 'Micro-ATX', memoryType: 'DDR3' }, compatibility: { category: 'MOTHERBOARD', socket: 'LGA1150', formFactor: 'Micro-ATX' } },
  { sku: 'MB-INT-H110', categorySlug: 'motherboards', name: 'Generic H110 Motherboard LGA1151', slug: 'generic-h110-lga1151', brand: 'Generic', basePrice: 5500, description: 'Motherboard for 6th and 7th Gen Intel with DDR4 support.', specs: { socket: 'LGA1151', chipset: 'H110', formFactor: 'Micro-ATX', memoryType: 'DDR4' }, compatibility: { category: 'MOTHERBOARD', socket: 'LGA1151', formFactor: 'Micro-ATX' } },
  { sku: 'MB-INT-H310', categorySlug: 'motherboards', name: 'Gigabyte H310M DS2 LGA1151', slug: 'gigabyte-h310m-ds2', brand: 'GIGABYTE', basePrice: 8500, description: 'For 8th and 9th Gen Intel budget builds.', specs: { socket: 'LGA1151', chipset: 'H310', formFactor: 'Micro-ATX', memoryType: 'DDR4' }, compatibility: { category: 'MOTHERBOARD', socket: 'LGA1151', formFactor: 'Micro-ATX' } },

  // --- BUDGET RAM ---
  { sku: 'RAM-DDR3-4GB', categorySlug: 'memory', name: 'Generic 4GB DDR3 1333MHz', slug: 'generic-4gb-ddr3', brand: 'Generic', basePrice: 1100, description: 'The absolute bare minimum RAM stick.', specs: { capacity: '4GB', speed: '1333 MHz', memoryType: 'DDR3' }, compatibility: { category: 'RAM' } },
  { sku: 'RAM-DDR4-4GB', categorySlug: 'memory', name: 'Generic 4GB DDR4 2400MHz', slug: 'generic-4gb-ddr4', brand: 'Generic', basePrice: 2000, description: 'Cheap DDR4 for office builds.', specs: { capacity: '4GB', speed: '2400 MHz', memoryType: 'DDR4' }, compatibility: { category: 'RAM' } },
  { sku: 'RAM-DDR4-8GB-2666', categorySlug: 'memory', name: 'Crucial 8GB DDR4 2666MHz', slug: 'crucial-8gb-ddr4-2666', brand: 'Crucial', basePrice: 4500, description: 'Reliable DDR4 stick from Crucial.', specs: { capacity: '8GB', speed: '2666 MHz', memoryType: 'DDR4' }, compatibility: { category: 'RAM' } },

  // --- BUDGET STORAGE ---
  { sku: 'SSD-SATA-120GB', categorySlug: 'storage', name: 'Kingston A400 120GB SATA SSD', slug: 'kingston-a400-120gb', brand: 'Kingston', basePrice: 2800, description: 'Basic OS drive. Dramatically speeds up old PCs.', specs: { capacity: '120GB', type: 'SATA 2.5"', readSpeed: '500 MB/s' }, compatibility: { category: 'STORAGE' } },
  { sku: 'HDD-WD-500GB', categorySlug: 'storage', name: 'Western Digital 500GB HDD (Used)', slug: 'wd-500gb-hdd-used', brand: 'Western Digital', basePrice: 1400, description: 'Extremely cheap mass storage.', specs: { capacity: '500GB', type: '3.5" HDD', rpm: '7200 RPM' }, compatibility: { category: 'STORAGE' } },
  { sku: 'HDD-SEAGATE-1TB', categorySlug: 'storage', name: 'Seagate Barracuda 1TB HDD (Used)', slug: 'seagate-1tb-hdd-used', brand: 'Seagate', basePrice: 3500, description: 'Cheap 1 Terabyte drive for storing lots of games.', specs: { capacity: '1TB', type: '3.5" HDD', rpm: '7200 RPM' }, compatibility: { category: 'STORAGE' } },

  // --- BUDGET PSUs ---
  { sku: 'PSU-GENERIC-400W', categorySlug: 'power-supplies', name: 'Generic 400W Power Supply', slug: 'generic-400w-psu', brand: 'Generic', basePrice: 1800, description: 'Only use this for PCs without dedicated graphics cards.', specs: { wattage: '400W', efficiency: 'None', modularity: 'Non-Modular' }, compatibility: { category: 'PSU', wattage: 400 } },
  { sku: 'PSU-CORSAIR-VS450', categorySlug: 'power-supplies', name: 'Corsair VS450 450W (Used)', slug: 'corsair-vs450-used', brand: 'Corsair', basePrice: 5500, description: 'Used but reliable power supply from a good brand.', specs: { wattage: '450W', efficiency: '80+ White', modularity: 'Non-Modular' }, compatibility: { category: 'PSU', wattage: 450 } },
  { sku: 'PSU-AEROCOOL-500W', categorySlug: 'power-supplies', name: 'Aerocool VX PLUS 500W', slug: 'aerocool-vx-plus-500w', brand: 'AeroCool', basePrice: 6500, description: 'Entry level brand new power supply for budget GPUs like RX 570.', specs: { wattage: '500W', efficiency: 'Standard', modularity: 'Non-Modular' }, compatibility: { category: 'PSU', wattage: 500 } },

  // --- BUDGET CASES ---
  { sku: 'CASE-OFFICE-BLACK', categorySlug: 'cases', name: 'Standard Office ATX Case (Used)', slug: 'standard-office-atx-used', brand: 'Generic', basePrice: 1500, description: 'Literally just a metal box to hold your parts.', specs: { type: 'Mid Tower', color: 'Black', includedFans: 'None' }, compatibility: { category: 'CASE', formFactor: 'ATX' } },
  { sku: 'CASE-EASE-RGB', categorySlug: 'cases', name: 'EASE EOC3 ATX Case with RGB strip', slug: 'ease-eoc3-rgb', brand: 'EASE', basePrice: 5500, description: 'Cheap case with some RGB flair.', specs: { type: 'Mid Tower', color: 'Black', includedFans: '1x Rear' }, compatibility: { category: 'CASE', formFactor: 'ATX' } },
  { sku: 'CASE-THUNDER-BLACKOUT', categorySlug: 'cases', name: 'Thunder Blackout Micro-ATX', slug: 'thunder-blackout-matx', brand: 'Thunder', basePrice: 7500, description: 'Clean stealth look for budget builds.', specs: { type: 'Mini Tower', color: 'Black', includedFans: '2x 120mm' }, compatibility: { category: 'CASE', formFactor: 'Micro-ATX' } },

  // --- BUDGET LAPTOPS (USED BUSINESS) ---
  { sku: 'LAP-LEN-T440', categorySlug: 'laptops', name: 'Lenovo ThinkPad T440 (Used)', slug: 'lenovo-thinkpad-t440-used', brand: 'Lenovo', basePrice: 28000, description: 'Old but gold. Core i5 4th Gen for basic typing and web browsing.', specs: { cpu: 'Core i5-4300U', ram: '8GB', storage: '128GB SSD', display: '14" HD' }, compatibility: { category: 'LAPTOP' } },
  { sku: 'LAP-DELL-LAT-E5450', categorySlug: 'laptops', name: 'Dell Latitude E5450 (Used)', slug: 'dell-latitude-e5450-used', brand: 'Dell', basePrice: 35000, description: 'Sturdy business laptop with Core i5 5th Gen.', specs: { cpu: 'Core i5-5300U', ram: '8GB', storage: '256GB SSD', display: '14" HD' }, compatibility: { category: 'LAPTOP' } },
  { sku: 'LAP-HP-ELITE-840-G3', categorySlug: 'laptops', name: 'HP EliteBook 840 G3 (Used)', slug: 'hp-elitebook-840-g3-used', brand: 'HP', basePrice: 45000, description: 'Sleek silver metal design with Core i5 6th Gen.', specs: { cpu: 'Core i5-6200U', ram: '8GB', storage: '256GB SSD', display: '14" FHD' }, compatibility: { category: 'LAPTOP' } },

  // --- BUDGET MONITORS ---
  { sku: 'MON-GENERIC-19', categorySlug: 'monitors', name: 'Generic 19" LCD Monitor (Used)', slug: 'generic-19-lcd-used', brand: 'Generic', basePrice: 5500, description: 'Standard 19-inch squarish or widescreen monitor for CCTV or extreme budget PCs.', specs: { size: '19"', resolution: '1366x768', refreshRate: '60Hz', panel: 'TN' }, compatibility: { category: 'MONITOR' } },
  { sku: 'MON-GENERIC-24', categorySlug: 'monitors', name: 'Generic 24" 1080p Monitor (Used)', slug: 'generic-24-1080p-used', brand: 'Generic', basePrice: 12500, description: 'Random branded 24 inch 1080p monitor.', specs: { size: '24"', resolution: '1920x1080', refreshRate: '60Hz', panel: 'TN' }, compatibility: { category: 'MONITOR' } },

  // --- BUDGET PERIPHERALS ---
  { sku: 'MICE-REDRAGON-M601', categorySlug: 'mice', name: 'Redragon M601 Centrophorus', slug: 'redragon-m601-centrophorus', brand: 'Redragon', basePrice: 3500, description: 'One of the best cheap gaming mice you can buy.', specs: { sensor: 'Optical', dpi: '3200', connection: 'Wired' }, compatibility: { category: 'MOUSE' } },
  { sku: 'KB-GENERIC-OFFICE', categorySlug: 'keyboards', name: 'Generic Office Keyboard', slug: 'generic-office-keyboard', brand: 'Generic', basePrice: 600, description: 'It types.', specs: { type: 'Membrane', connection: 'Wired' }, compatibility: { category: 'KEYBOARD' } },
  { sku: 'HP-A4TECH-HS30', categorySlug: 'headphones', name: 'A4Tech HS-30 Headset', slug: 'a4tech-hs-30', brand: 'A4Tech', basePrice: 2200, description: 'Cheap and surprisingly decent headset for office calls and basic gaming.', specs: { connection: '3.5mm Wired', microphone: 'Fixed' }, compatibility: { category: 'HEADPHONES' } },
  { sku: 'PAD-GENERIC-EXTENDED', categorySlug: 'mice', name: 'Generic Extended Gaming Mousepad map design', slug: 'generic-extended-mousepad-map', brand: 'Generic', basePrice: 1500, description: 'You know exactly which mousepad this is.', specs: { type: 'Extended Desk Mat', connection: 'None' }, compatibility: { category: 'MOUSE' } },
  { sku: 'MICE-LOGI-M170', categorySlug: 'mice', name: 'Logitech M170 Wireless Mouse', slug: 'logitech-m170-wireless', brand: 'Logitech', basePrice: 2800, description: 'Simple, reliable wireless mouse for laptops.', specs: { sensor: 'Optical', connection: 'Wireless' }, compatibility: { category: 'MOUSE' } }
];
