export const extraProducts3 = [
  // --- LAPTOPS ---
  { sku: 'LAP-ACER-PRED-17', categorySlug: 'laptops', name: 'Acer Predator Helios 300 17.3"', slug: 'acer-predator-helios-300-17', brand: 'Acer', basePrice: 345000, description: 'Massive 17-inch screen for immersive gaming. Intel Core i7 12th Gen and RTX 3060.', specs: { cpu: 'Core i7-12700H', ram: '16GB', gpu: 'RTX 3060 6GB', display: '17.3" FHD 144Hz' }, compatibility: { category: 'LAPTOP' } },
  { sku: 'LAP-DELL-G15', categorySlug: 'laptops', name: 'Dell G15 5530 Gaming Laptop', slug: 'dell-g15-5530', brand: 'Dell', basePrice: 285000, description: 'Alienware-inspired thermal design. Core i7-13650HX and RTX 4050 graphics.', specs: { cpu: 'Core i7-13650HX', ram: '16GB', gpu: 'RTX 4050 6GB', display: '15.6" FHD 165Hz' }, compatibility: { category: 'LAPTOP' } },
  { sku: 'LAP-ASUS-VIVOBOOK-PRO', categorySlug: 'laptops', name: 'ASUS VivoBook Pro 15 OLED', slug: 'asus-vivobook-pro-15-oled', brand: 'ASUS', basePrice: 245000, description: 'Perfect for creators. Stunning OLED display paired with Ryzen 7 and RTX 3050.', specs: { cpu: 'Ryzen 7 5800H', ram: '16GB', gpu: 'RTX 3050 4GB', display: '15.6" FHD OLED' }, compatibility: { category: 'LAPTOP' } },
  { sku: 'LAP-MAC-M1-AIR', categorySlug: 'laptops', name: 'Apple MacBook Air 13" M1', slug: 'apple-macbook-air-13-m1', brand: 'Apple', basePrice: 215000, description: 'The undisputed king of value and battery life for productivity.', specs: { cpu: 'Apple M1', ram: '8GB', storage: '256GB SSD', display: '13.3" Retina' }, compatibility: { category: 'LAPTOP' } },
  
  // --- DESKTOPS ---
  { sku: 'DESK-THUNDER-PREBUILT', categorySlug: 'desktops', name: 'Thunder Elite Prebuilt Gaming PC', slug: 'thunder-elite-prebuilt', brand: 'Thunder', basePrice: 155000, description: 'Budget friendly local prebuilt featuring Core i5 12400F and GTX 1660 Super. Perfect for 1080p Esports.', specs: { cpu: 'Core i5-12400F', ram: '16GB', gpu: 'GTX 1660 Super', storage: '512GB NVMe SSD' }, compatibility: { category: 'DESKTOP' } },
  { sku: 'DESK-LEN-LEGION-T5', categorySlug: 'desktops', name: 'Lenovo Legion Tower 5i', slug: 'lenovo-legion-tower-5i', brand: 'Lenovo', basePrice: 385000, description: 'Powerful prebuilt from Lenovo featuring aggressive airflow, Core i7 13700F, and RTX 4060 Ti.', specs: { cpu: 'Core i7-13700F', ram: '16GB', gpu: 'RTX 4060 Ti 8GB', storage: '1TB NVMe SSD' }, compatibility: { category: 'DESKTOP' } },

  // --- MOTHERBOARDS ---
  { sku: 'MB-GIG-B760M-DS3H', categorySlug: 'motherboards', name: 'GIGABYTE B760M DS3H DDR4', slug: 'gigabyte-b760m-ds3h-ddr4', brand: 'GIGABYTE', basePrice: 32000, description: 'Excellent budget micro-ATX board for Intel 12th and 13th Gen processors.', specs: { socket: 'LGA1700', chipset: 'B760', formFactor: 'Micro-ATX', memoryType: 'DDR4' }, compatibility: { category: 'MOTHERBOARD', socket: 'LGA1700', formFactor: 'Micro-ATX' } },
  { sku: 'MB-MSI-MAG-B650', categorySlug: 'motherboards', name: 'MSI MAG B650 TOMAHAWK WIFI', slug: 'msi-mag-b650-tomahawk-wifi', brand: 'MSI', basePrice: 68000, description: 'Military-styled, durable AM5 motherboard with excellent VRM cooling and built-in WiFi 6E.', specs: { socket: 'AM5', chipset: 'B650', formFactor: 'ATX', memoryType: 'DDR5' }, compatibility: { category: 'MOTHERBOARD', socket: 'AM5', formFactor: 'ATX' } },

  // --- PROCESSORS ---
  { sku: 'CPU-AMD-5600G', categorySlug: 'processors', name: 'AMD Ryzen 5 5600G with Radeon Graphics', slug: 'amd-ryzen-5-5600g', brand: 'AMD', basePrice: 35000, description: 'The absolute best budget APU for PC builders without a dedicated graphics card.', specs: { cores: '6', threads: '12', socket: 'AM4', integratedGpu: 'Radeon Vega 7' }, compatibility: { category: 'CPU', socket: 'AM4', tdp: 65, includesCooler: true } },
  { sku: 'CPU-INT-13100F', categorySlug: 'processors', name: 'Intel Core i3-13100F Processor', slug: 'intel-core-i3-13100f', brand: 'Intel', basePrice: 28000, description: 'Entry-level 13th Gen powerhouse. 4 cores and 8 threads of fast gaming performance.', specs: { cores: '4', threads: '8', socket: 'LGA1700' }, compatibility: { category: 'CPU', socket: 'LGA1700', tdp: 58, includesCooler: true } },

  // --- GPUS ---
  { sku: 'GPU-GALAX-3060', categorySlug: 'gpus', name: 'GALAX GeForce RTX 3060 1-Click OC 8GB', slug: 'galax-rtx-3060-8gb', brand: 'GALAX', basePrice: 78000, description: 'Affordable entry to RTX gaming and DLSS. 8GB VRAM version.', specs: { vram: '8GB' }, compatibility: { category: 'GPU', tdp: 170 } },
  { sku: 'GPU-POWERCOLOR-6700XT', categorySlug: 'gpus', name: 'PowerColor Fighter AMD Radeon RX 6700 XT', slug: 'powercolor-rx-6700-xt', brand: 'PowerColor', basePrice: 95000, description: 'Raw rasterization beast for 1440p gaming. Incredible price-to-performance ratio.', specs: { vram: '12GB' }, compatibility: { category: 'GPU', tdp: 230 } },

  // --- MONITORS ---
  { sku: 'MON-DELL-ALIEN-34-V2', categorySlug: 'monitors', name: 'Alienware 34 Curved QD-OLED (AW3423DWF)', slug: 'alienware-aw3423dwf-v2', brand: 'Dell Alienware', basePrice: 280000, description: 'The ultimate ultrawide gaming experience. Quantum Dot OLED panel with deep blacks and infinite contrast.', specs: { size: '34"', resolution: '3440x1440', refreshRate: '165Hz', panel: 'QD-OLED' }, compatibility: { category: 'MONITOR' } },
  { sku: 'MON-EASE-24', categorySlug: 'monitors', name: 'EASE G24I16 24" IPS 165Hz Gaming Monitor', slug: 'ease-g24i16', brand: 'EASE', basePrice: 38000, description: 'Excellent budget IPS gaming monitor popular in the local market. Fast 165Hz refresh rate.', specs: { size: '24"', resolution: '1920x1080', refreshRate: '165Hz', panel: 'IPS' }, compatibility: { category: 'MONITOR' } },
  { sku: 'MON-GIG-G24F2-V2', categorySlug: 'monitors', name: 'GIGABYTE G24F 2 24" 165Hz (180Hz OC) Gaming Monitor', slug: 'gigabyte-g24f-2-v2', brand: 'GIGABYTE', basePrice: 52000, description: 'Premium 1080p gaming display with wide color gamut and fast response times.', specs: { size: '24"', resolution: '1920x1080', refreshRate: '180Hz OC', panel: 'SS IPS' }, compatibility: { category: 'MONITOR' } },

  // --- KEYBOARDS ---
  { sku: 'KB-REDRAGON-K617', categorySlug: 'keyboards', name: 'Redragon K617 Fizz 60% Wired RGB', slug: 'redragon-k617-fizz', brand: 'Redragon', basePrice: 6500, description: 'The most popular budget 60% mechanical keyboard in Pakistan. Linear red switches.', specs: { size: '60%', switches: 'Linear Red', lighting: 'RGB' }, compatibility: { category: 'KEYBOARD' } },
  { sku: 'KB-KEYCHRON-V1', categorySlug: 'keyboards', name: 'Keychron V1 QMK Custom Mechanical Keyboard', slug: 'keychron-v1', brand: 'Keychron', basePrice: 28000, description: 'Fully customizable 75% mechanical keyboard with hot-swappable switches and QMK/VIA support.', specs: { size: '75%', switches: 'Key K Pro Red', lighting: 'South-facing RGB' }, compatibility: { category: 'KEYBOARD' } },

  // --- MICE ---
  { sku: 'MICE-LOGI-G102', categorySlug: 'mice', name: 'Logitech G102 Lightsync Gaming Mouse', slug: 'logitech-g102-lightsync', brand: 'Logitech', basePrice: 4500, description: 'The classic entry-level gaming mouse. Lightweight, accurate sensor, and beautiful RGB.', specs: { sensor: 'Optical', dpi: '8000', connection: 'Wired' }, compatibility: { category: 'MOUSE' } },
  { sku: 'MICE-GLORIOUS-MODELO-V2', categorySlug: 'mice', name: 'Glorious Model O Wireless V2', slug: 'glorious-model-o-wireless-v2', brand: 'Glorious', basePrice: 18500, description: 'Ultra-lightweight honeycomb design with lag-free wireless technology.', specs: { sensor: 'BAMF', weight: '69g', connection: 'Wireless' }, compatibility: { category: 'MOUSE' } },

  // --- HEADPHONES ---
  { sku: 'HP-RAZER-KRAKEN-X', categorySlug: 'headphones', name: 'Razer Kraken X Multi-Platform', slug: 'razer-kraken-x', brand: 'Razer', basePrice: 12500, description: 'Ultra-lightweight comfort for marathon gaming. 7.1 surround sound software included.', specs: { connection: '3.5mm Wired', surround: '7.1 Virtual' }, compatibility: { category: 'HEADPHONES' } },
  { sku: 'HP-STEEL-ARCTIS-NOVA1', categorySlug: 'headphones', name: 'SteelSeries Arctis Nova 1', slug: 'steelseries-arctis-nova-1', brand: 'SteelSeries', basePrice: 16000, description: 'High fidelity audio in a lightweight, modern design. ClearCast Gen 2 mic.', specs: { connection: '3.5mm Wired', microphone: 'Retractable Noise-Cancelling' }, compatibility: { category: 'HEADPHONES' } },

  // --- CASES ---
  { sku: 'CASE-THUNDER-ARMOR', categorySlug: 'cases', name: 'Thunder Armor ATX Gaming Case', slug: 'thunder-armor-atx', brand: 'Thunder', basePrice: 12500, description: 'Budget local favorite. Mesh front panel with 4 pre-installed ARGB fans for maximum airflow.', specs: { type: 'Mid Tower', color: 'Black', includedFans: '4x ARGB' }, compatibility: { category: 'CASE', formFactor: 'ATX' } },
  { sku: 'CASE-NZXT-H9-FLOW', categorySlug: 'cases', name: 'NZXT H9 Flow Dual-Chamber', slug: 'nzxt-h9-flow', brand: 'NZXT', basePrice: 48000, description: 'Incredible dual-chamber design with seamless glass panels and massive cooling support.', specs: { type: 'Mid Tower', color: 'White', sidePanel: 'Tempered Glass' }, compatibility: { category: 'CASE', formFactor: 'ATX' } },

  // --- COOLERS ---
  { sku: 'COOL-ID-SE214XT', categorySlug: 'coolers', name: 'ID-COOLING SE-214-XT ARGB', slug: 'id-cooling-se-214-xt', brand: 'ID-COOLING', basePrice: 5500, description: 'The absolute best value air cooler in the market. Beats stock coolers easily and looks great.', specs: { type: 'Air Cooler', fans: '1x 120mm' }, compatibility: { category: 'COOLER' } },
  { sku: 'COOL-DEEPCOOL-LT720', categorySlug: 'coolers', name: 'DeepCool LT720 360mm Liquid Cooler', slug: 'deepcool-lt720', brand: 'DeepCool', basePrice: 36000, description: 'High-performance 360mm AIO with a unique infinity mirror pump block design.', specs: { type: 'Liquid AIO', size: '360mm' }, compatibility: { category: 'COOLER' } },

  // --- RAM ---
  { sku: 'RAM-XPG-D50-16GB', categorySlug: 'memory', name: 'XPG Spectrix D50 16GB (2x8GB) 3200MHz', slug: 'xpg-spectrix-d50-16gb', brand: 'ADATA XPG', basePrice: 12500, description: 'Elegant geometric styling with solid RGB lighting and reliable performance.', specs: { capacity: '16GB', speed: '3200 MHz', memoryType: 'DDR4' }, compatibility: { category: 'RAM' } },
  { sku: 'RAM-GSKILL-TRIDENTZ5-32GB', categorySlug: 'memory', name: 'G.Skill Trident Z5 RGB 32GB (2x16GB) 6000MHz', slug: 'gskill-trident-z5-rgb-32gb', brand: 'G.Skill', basePrice: 36000, description: 'Top tier DDR5 memory optimized for the latest Intel and AMD platforms.', specs: { capacity: '32GB', speed: '6000 MHz', memoryType: 'DDR5' }, compatibility: { category: 'RAM' } },

  // --- STORAGE ---
  { sku: 'SSD-LEXAR-NM620', categorySlug: 'storage', name: 'Lexar NM620 512GB NVMe', slug: 'lexar-nm620-512gb', brand: 'Lexar', basePrice: 9500, description: 'Fast and reliable Gen3 NVMe SSD. Perfect for budget builds and OS drives.', specs: { capacity: '512GB', type: 'Gen3 NVMe', readSpeed: '3500 MB/s' }, compatibility: { category: 'STORAGE' } },
  { sku: 'SSD-KINGSTON-NV2-1TB', categorySlug: 'storage', name: 'Kingston NV2 1TB PCIe 4.0 NVMe', slug: 'kingston-nv2-1tb', brand: 'Kingston', basePrice: 16500, description: 'Excellent value Gen4 storage offering massive capacity for modern games.', specs: { capacity: '1TB', type: 'Gen4 NVMe', readSpeed: '3500 MB/s' }, compatibility: { category: 'STORAGE' } },

  // --- POWER SUPPLIES ---
  { sku: 'PSU-CORSAIR-CX650-V2', categorySlug: 'power-supplies', name: 'Corsair CX650 650W 80 Plus Bronze', slug: 'corsair-cx650-v2', brand: 'Corsair', basePrice: 18500, description: 'Reliable power for mid-range builds from a highly trusted brand.', specs: { wattage: '650W', efficiency: '80+ Bronze', modularity: 'Non-Modular' }, compatibility: { category: 'PSU', wattage: 650 } },
  { sku: 'PSU-XPG-CORE-REACTOR-850', categorySlug: 'power-supplies', name: 'XPG Core Reactor 850W 80 Plus Gold', slug: 'xpg-core-reactor-850', brand: 'ADATA XPG', basePrice: 32000, description: 'Fully modular, highly efficient power supply ready for high-end RTX 40-series cards.', specs: { wattage: '850W', efficiency: '80+ Gold', modularity: 'Fully Modular' }, compatibility: { category: 'PSU', wattage: 850 } }
];
