export const extraProducts = [
  // --- LAPTOPS (Massive expansion) ---
  { sku: 'LAP-HP-ENVY-14', categorySlug: 'laptops', name: 'HP Envy 14-inch Laptop', slug: 'hp-envy-14', brand: 'HP', basePrice: 280000, description: 'Premium ultra-portable laptop. Intel Core i7-1260P, 16GB RAM, 512GB SSD, 14-inch 2.2K Display. Perfect for creators on the go.', specs: { cpu: 'Core i7-1260P', ram: '16GB', display: '14" 2.2K' }, compatibility: { category: 'LAPTOP' } },
  { sku: 'LAP-DELL-XPS15', categorySlug: 'laptops', name: 'Dell XPS 15 9530', slug: 'dell-xps-15-9530', brand: 'Dell', basePrice: 620000, description: 'The absolute standard for premium Windows laptops. 13th Gen Core i9, RTX 4070, and a stunning 3.5K OLED touch display.', specs: { cpu: 'Core i9-13900H', ram: '32GB', gpu: 'RTX 4070', display: '15.6" 3.5K OLED' }, compatibility: { category: 'LAPTOP' } },
  { sku: 'LAP-MSI-THIN', categorySlug: 'laptops', name: 'MSI Thin GF63', slug: 'msi-thin-gf63', brand: 'MSI', basePrice: 195000, description: 'Lightweight budget gaming. Intel Core i5-12450H paired with RTX 2050. Easy to carry and capable of eSports gaming.', specs: { cpu: 'Core i5-12450H', ram: '8GB', gpu: 'RTX 2050', display: '15.6" 144Hz' }, compatibility: { category: 'LAPTOP' } },
  { sku: 'LAP-ASUS-ZEPH-G14', categorySlug: 'laptops', name: 'ASUS ROG Zephyrus G14 (2023)', slug: 'asus-rog-zephyrus-g14-2023', brand: 'ASUS', basePrice: 430000, description: 'The 14-inch beast. AMD Ryzen 9 7940HS, RTX 4060, AniMe Matrix LED display on the lid, and Nebula Display.', specs: { cpu: 'Ryzen 9 7940HS', ram: '16GB', gpu: 'RTX 4060', display: '14" QHD+ 165Hz' }, compatibility: { category: 'LAPTOP' } },
  { sku: 'LAP-LEN-YOGA', categorySlug: 'laptops', name: 'Lenovo Yoga 7i 2-in-1', slug: 'lenovo-yoga-7i', brand: 'Lenovo', basePrice: 245000, description: 'Flexible creativity. 13th Gen Core i7, 16GB RAM, 1TB SSD, 16-inch 2.5K Touch display. Folds into a tablet.', specs: { cpu: 'Core i7-1355U', ram: '16GB', formFactor: '2-in-1 Convertible' }, compatibility: { category: 'LAPTOP' } },
  { sku: 'LAP-MAC-M3-MAX', categorySlug: 'laptops', name: 'Apple MacBook Pro 16" M3 Max', slug: 'apple-macbook-pro-16-m3-max', brand: 'Apple', basePrice: 1250000, description: 'Incredible performance for professionals. 16-core CPU, 40-core GPU, 48GB Unified Memory. The ultimate Mac.', specs: { cpu: 'M3 Max 16-Core', ram: '48GB', display: '16" XDR' }, compatibility: { category: 'LAPTOP' } },
  { sku: 'LAP-HP-SPECTRE', categorySlug: 'laptops', name: 'HP Spectre x360 14', slug: 'hp-spectre-x360-14', brand: 'HP', basePrice: 380000, description: 'Gorgeous gem-cut design, OLED display, and incredible battery life. Includes HP Tilt Pen.', specs: { cpu: 'Core Ultra 7', ram: '16GB', display: '14" OLED Touch' }, compatibility: { category: 'LAPTOP' } },
  { sku: 'LAP-ASUS-TUF-A15', categorySlug: 'laptops', name: 'ASUS TUF Gaming A15', slug: 'asus-tuf-a15', brand: 'ASUS', basePrice: 285000, description: 'Rugged and powerful. Ryzen 7 7735HS, RTX 4050, Military-grade toughness.', specs: { cpu: 'Ryzen 7 7735HS', ram: '16GB', gpu: 'RTX 4050' }, compatibility: { category: 'LAPTOP' } },
  { sku: 'LAP-ACER-PREDATOR', categorySlug: 'laptops', name: 'Acer Predator Helios Neo 16', slug: 'acer-predator-helios-neo-16', brand: 'Acer', basePrice: 360000, description: 'High-end gaming performance. Core i7-13700HX, RTX 4060, aggressive styling.', specs: { cpu: 'Core i7-13700HX', ram: '16GB', gpu: 'RTX 4060' }, compatibility: { category: 'LAPTOP' } },
  { sku: 'LAP-RAZER-BLADE15', categorySlug: 'laptops', name: 'Razer Blade 15', slug: 'razer-blade-15', brand: 'Razer', basePrice: 590000, description: 'The thinnest and sharpest gaming laptop. CNC aluminum body, Core i7, RTX 4070.', specs: { cpu: 'Core i7-13800H', ram: '16GB', gpu: 'RTX 4070' }, compatibility: { category: 'LAPTOP' } },

  // --- CPUs ---
  { sku: 'AMD-7950X', categorySlug: 'processors', name: 'AMD Ryzen 9 7950X', slug: 'amd-ryzen-9-7950x', brand: 'AMD', basePrice: 165000, description: '16 cores and 32 threads. The pinnacle of desktop productivity and gaming on AM5.', specs: { cores: 16, threads: 32, boostClock: '5.7 GHz' }, compatibility: { category: 'CPU', socket: 'AM5', tdp: 170, includesCooler: false } },
  { sku: 'INT-13900K', categorySlug: 'processors', name: 'Intel Core i9-13900K', slug: 'intel-core-i9-13900k', brand: 'Intel', basePrice: 155000, description: '24 cores, 32 threads, blazing fast performance for any workload.', specs: { cores: 24, threads: 32, boostClock: '5.8 GHz' }, compatibility: { category: 'CPU', socket: 'LGA1700', tdp: 125, includesCooler: false } },
  { sku: 'AMD-7700X', categorySlug: 'processors', name: 'AMD Ryzen 7 7700X', slug: 'amd-ryzen-7-7700x', brand: 'AMD', basePrice: 95000, description: '8 cores of pure AM5 performance.', specs: { cores: 8, threads: 16, boostClock: '5.4 GHz' }, compatibility: { category: 'CPU', socket: 'AM5', tdp: 105, includesCooler: false } },
  { sku: 'INT-12100F', categorySlug: 'processors', name: 'Intel Core i3-12100F', slug: 'intel-core-i3-12100f', brand: 'Intel', basePrice: 24000, description: 'The absolute best ultra-budget gaming CPU.', specs: { cores: 4, threads: 8, boostClock: '4.3 GHz' }, compatibility: { category: 'CPU', socket: 'LGA1700', tdp: 58, includesCooler: true } },
  { sku: 'AMD-5800X3D', categorySlug: 'processors', name: 'AMD Ryzen 7 5800X3D', slug: 'amd-ryzen-7-5800x3d', brand: 'AMD', basePrice: 85000, description: 'Legendary AM4 gaming processor with 3D V-Cache.', specs: { cores: 8, threads: 16, cache: '96MB' }, compatibility: { category: 'CPU', socket: 'AM4', tdp: 105, includesCooler: false } },

  // --- GPUs ---
  { sku: 'ASUS-4060-DUAL', categorySlug: 'gpus', name: 'ASUS Dual GeForce RTX 4060', slug: 'asus-dual-rtx-4060', brand: 'ASUS', basePrice: 96000, description: 'Quiet, cool, and compact 1080p gaming.', specs: { vram: '8GB' }, compatibility: { category: 'GPU', tdp: 115 } },
  { sku: 'MSI-4070-VENTUS', categorySlug: 'gpus', name: 'MSI GeForce RTX 4070 Ventus 3X', slug: 'msi-rtx-4070-ventus-3x', brand: 'MSI', basePrice: 185000, description: 'Triple fan cooling, excellent 1440p performance.', specs: { vram: '12GB' }, compatibility: { category: 'GPU', tdp: 200 } },
  { sku: 'ZOT-4090-AMP', categorySlug: 'gpus', name: 'ZOTAC GAMING GeForce RTX 4090 AMP Extreme AIRO', slug: 'zotac-rtx-4090-amp', brand: 'ZOTAC', basePrice: 620000, description: 'Aerodynamic inspired design with unbelievable 4K performance.', specs: { vram: '24GB' }, compatibility: { category: 'GPU', tdp: 450 } },
  { sku: 'SAP-7900XT-PULSE', categorySlug: 'gpus', name: 'Sapphire PULSE AMD Radeon RX 7900 XT', slug: 'sapphire-pulse-rx-7900-xt', brand: 'Sapphire', basePrice: 245000, description: 'Value oriented ultra-high-end AMD graphics.', specs: { vram: '20GB' }, compatibility: { category: 'GPU', tdp: 315 } },
  { sku: 'GIG-4060TI-EAGLE', categorySlug: 'gpus', name: 'GIGABYTE GeForce RTX 4060 Ti EAGLE OC', slug: 'gigabyte-rtx-4060-ti-eagle', brand: 'GIGABYTE', basePrice: 122000, description: 'Great 1080p/1440p entry card with Windforce cooling.', specs: { vram: '8GB' }, compatibility: { category: 'GPU', tdp: 160 } },
  { sku: 'XFX-7800XT-QICK', categorySlug: 'gpus', name: 'XFX Speedster QICK 319 Radeon RX 7800 XT', slug: 'xfx-rx-7800-xt-qick', brand: 'XFX', basePrice: 165000, description: 'Clean stealth aesthetic, massive 1440p gaming value.', specs: { vram: '16GB' }, compatibility: { category: 'GPU', tdp: 263 } },

  // --- MOTHERBOARDS ---
  { sku: 'ASUS-ROG-X670E', categorySlug: 'motherboards', name: 'ASUS ROG Crosshair X670E Hero', slug: 'asus-rog-x670e-hero', brand: 'ASUS', basePrice: 185000, description: 'The absolute pinnacle of AM5 motherboards.', specs: { chipset: 'X670E', formFactor: 'ATX' }, compatibility: { category: 'MOTHERBOARD', socket: 'AM5', formFactor: 'ATX' } },
  { sku: 'MSI-B550-TOM', categorySlug: 'motherboards', name: 'MSI MAG B550 TOMAHAWK', slug: 'msi-mag-b550-tomahawk', brand: 'MSI', basePrice: 45000, description: 'Military grade AM4 ATX motherboard.', specs: { chipset: 'B550', formFactor: 'ATX' }, compatibility: { category: 'MOTHERBOARD', socket: 'AM4', formFactor: 'ATX' } },
  { sku: 'GIG-Z790-AORUS-ELITE', categorySlug: 'motherboards', name: 'GIGABYTE Z790 AORUS ELITE AX', slug: 'gigabyte-z790-aorus-elite-ax', brand: 'GIGABYTE', basePrice: 78000, description: 'Feature rich LGA1700 board for Intel 13th/14th Gen.', specs: { chipset: 'Z790', formFactor: 'ATX' }, compatibility: { category: 'MOTHERBOARD', socket: 'LGA1700', formFactor: 'ATX' } },
  { sku: 'ASUS-PRIME-H610M', categorySlug: 'motherboards', name: 'ASUS PRIME H610M-E D4', slug: 'asus-prime-h610m', brand: 'ASUS', basePrice: 22000, description: 'Budget LGA1700 board for office and entry gaming.', specs: { chipset: 'H610', formFactor: 'Micro-ATX' }, compatibility: { category: 'MOTHERBOARD', socket: 'LGA1700', formFactor: 'Micro-ATX' } },

  // --- MONITORS ---
  { sku: 'MON-GIG-M27Q', categorySlug: 'monitors', name: 'Gigabyte M27Q 27" 170Hz KVM Gaming Monitor', slug: 'gigabyte-m27q', brand: 'GIGABYTE', basePrice: 85000, description: '1440p, 170Hz, built in KVM switch. Incredible value.', specs: { resolution: '2560x1440', refreshRate: '170Hz' }, compatibility: { category: 'MONITOR' } },
  { sku: 'MON-ASUS-PG27AQDM', categorySlug: 'monitors', name: 'ASUS ROG Swift OLED PG27AQDM', slug: 'asus-rog-oled-pg27', brand: 'ASUS', basePrice: 290000, description: '240Hz 1440p OLED. Perfect competitive gaming monitor.', specs: { resolution: '2560x1440', refreshRate: '240Hz', panel: 'OLED' }, compatibility: { category: 'MONITOR' } },
  { sku: 'MON-DELL-S2722DGM', categorySlug: 'monitors', name: 'Dell 27 Curved Gaming Monitor S2722DGM', slug: 'dell-s2722dgm', brand: 'Dell', basePrice: 65000, description: '1440p 165Hz VA curved monitor.', specs: { resolution: '2560x1440', refreshRate: '165Hz' }, compatibility: { category: 'MONITOR' } },

  // --- RAM ---
  { sku: 'COR-VEN-64GB-D5', categorySlug: 'memory', name: 'Corsair Vengeance RGB 64GB (2x32GB) DDR5 5600MHz', slug: 'corsair-vengeance-rgb-64gb-ddr5', brand: 'Corsair', basePrice: 65000, description: 'Massive capacity for rendering and heavy multitasking.', specs: { speed: '5600 MHz' }, compatibility: { category: 'RAM' } },
  { sku: 'GSK-RIP-16GB-D4', categorySlug: 'memory', name: 'G.Skill Ripjaws V 16GB (2x8GB) DDR4 3600MHz', slug: 'gskill-ripjaws-v-16gb-ddr4', brand: 'G.Skill', basePrice: 14000, description: 'Classic red/black builds staple.', specs: { speed: '3600 MHz' }, compatibility: { category: 'RAM' } },

  // --- STORAGE ---
  { sku: 'SAM-980-PRO-1TB', categorySlug: 'storage', name: 'Samsung 980 PRO 1TB PCIe Gen4 NVMe', slug: 'samsung-980-pro-1tb', brand: 'Samsung', basePrice: 22000, description: 'Reliable fast Gen4 storage.', specs: { capacity: '1TB', readSpeed: '7000 MB/s' }, compatibility: { category: 'STORAGE' } },
  { sku: 'WD-BLUE-2TB-HDD', categorySlug: 'storage', name: 'WD Blue 2TB Desktop HDD', slug: 'wd-blue-2tb-hdd', brand: 'Western Digital', basePrice: 14500, description: 'Standard mass storage.', specs: { capacity: '2TB', speed: '7200 RPM' }, compatibility: { category: 'STORAGE' } },

  // --- CASES ---
  { sku: 'HYTE-Y60', categorySlug: 'cases', name: 'HYTE Y60 Modern Aesthetic Dual Chamber Case', slug: 'hyte-y60', brand: 'HYTE', basePrice: 58000, description: 'Panoramic glass case with vertical GPU mount included.', specs: { type: 'Mid Tower' }, compatibility: { category: 'CASE' } },
  { sku: 'FRACTAL-NORTH', categorySlug: 'cases', name: 'Fractal Design North ATX Case', slug: 'fractal-north', brand: 'Fractal Design', basePrice: 45000, description: 'Real walnut wood front panel. Sophisticated airflow case.', specs: { type: 'Mid Tower' }, compatibility: { category: 'CASE' } },

  // --- PSUS ---
  { sku: 'COR-RM750X', categorySlug: 'psus', name: 'Corsair RM750x 80 Plus Gold Fully Modular', slug: 'corsair-rm750x', brand: 'Corsair', basePrice: 35000, description: 'The gold standard in power supplies.', specs: { wattage: '750W' }, compatibility: { category: 'PSU' } },
  { sku: 'EVGA-600W', categorySlug: 'psus', name: 'EVGA 600 W1, 80+ WHITE 600W', slug: 'evga-600w1', brand: 'EVGA', basePrice: 12000, description: 'Cheap reliable power for budget systems.', specs: { wattage: '600W' }, compatibility: { category: 'PSU' } },

  // --- COOLERS ---
  { sku: 'NZXT-KRAKEN-360', categorySlug: 'coolers', name: 'NZXT Kraken 360 RGB', slug: 'nzxt-kraken-360', brand: 'NZXT', basePrice: 58000, description: 'LCD Screen pump head, top tier AIO cooling.', specs: { size: '360mm' }, compatibility: { category: 'COOLER' } },
  { sku: 'BEQ-DARKROCK-PRO4', categorySlug: 'coolers', name: 'be quiet! Dark Rock Pro 4', slug: 'bequiet-dark-rock-pro-4', brand: 'be quiet!', basePrice: 26000, description: 'Massive silent air cooler.', specs: { type: 'Air Cooler' }, compatibility: { category: 'COOLER' } },

  // --- PERIPHERALS & ACCESSORIES ---
  { sku: 'PER-LOGI-C922', categorySlug: 'peripherals', name: 'Logitech C922 Pro Stream Webcam', slug: 'logitech-c922', brand: 'Logitech', basePrice: 24000, description: '1080p streaming webcam.', specs: { resolution: '1080p' }, compatibility: { category: 'PERIPHERAL' } },
  { sku: 'PER-RAZ-SEIREN', categorySlug: 'peripherals', name: 'Razer Seiren Mini USB Mic', slug: 'razer-seiren-mini', brand: 'Razer', basePrice: 14000, description: 'Compact condenser mic.', specs: { type: 'Condenser' }, compatibility: { category: 'PERIPHERAL' } },
  { sku: 'PER-Xbox-Cont', categorySlug: 'peripherals', name: 'Xbox Wireless Controller - Carbon Black', slug: 'xbox-controller-black', brand: 'Microsoft', basePrice: 16500, description: 'The best PC controller.', specs: { connection: 'Bluetooth / Wireless' }, compatibility: { category: 'PERIPHERAL' } },

  // --- KEYBOARDS ---
  { sku: 'KB-COR-K70', categorySlug: 'keyboards', name: 'Corsair K70 RGB PRO Mechanical', slug: 'corsair-k70-pro', brand: 'Corsair', basePrice: 42000, description: 'Aluminum frame, Cherry MX Red switches.', specs: { switches: 'Cherry MX Red' }, compatibility: { category: 'KEYBOARD' } },
  { sku: 'KB-GLOR-GMMK', categorySlug: 'keyboards', name: 'Glorious GMMK Pro 75% Barebone', slug: 'glorious-gmmk-pro', brand: 'Glorious', basePrice: 55000, description: 'Enthusiast custom keyboard kit.', specs: { size: '75%' }, compatibility: { category: 'KEYBOARD' } },

  // --- MICE ---
  { sku: 'MS-RAZ-BASILISK', categorySlug: 'mice', name: 'Razer Basilisk V3', slug: 'razer-basilisk-v3', brand: 'Razer', basePrice: 18000, description: 'Customizable ergonomic gaming mouse.', specs: { sensor: 'Focus+ 26K' }, compatibility: { category: 'MOUSE' } },
  { sku: 'MS-LOGI-G305', categorySlug: 'mice', name: 'Logitech G305 LIGHTSPEED Wireless', slug: 'logitech-g305', brand: 'Logitech G', basePrice: 11000, description: 'Affordable wireless gaming.', specs: { sensor: 'HERO' }, compatibility: { category: 'MOUSE' } },

  // --- HEADPHONES ---
  { sku: 'HP-LOGI-G733', categorySlug: 'headphones', name: 'Logitech G733 LIGHTSPEED Wireless', slug: 'logitech-g733', brand: 'Logitech G', basePrice: 35000, description: 'Ultra-lightweight colorful wireless headset.', specs: { weight: '278g' }, compatibility: { category: 'HEADPHONE' } },
  { sku: 'HP-RAZ-KRAKEN', categorySlug: 'headphones', name: 'Razer Kraken V3 X', slug: 'razer-kraken-v3-x', brand: 'Razer', basePrice: 15000, description: 'Ultra-light USB gaming headset.', specs: { drivers: '40mm' }, compatibility: { category: 'HEADPHONE' } }
];
